@startuml
object "<u>phpDemo1:Folder</u>" as root {
    name = "php_demo1"
    subfolders =
        SourceFiles,
        IncludePath,
        RemoteFiles
    files = {}
}

object "<u>Source Files:Folder</u>" as SourceFiles {
    name = "Source Files"
    subfolders =
        phalcon,
        cache,
        public
    files = {}
}

object "<u>.phalcon:Folder</u>" as phalcon {
    name = ".phalcon"
    subfolders = 0
    files = 0
}

object "<u>cache:Folder</u>" as cache {
    name = "cache"
    subfolders = 0
    files = 0
}

object "<u>public:Folder</u>" as public {
    name = "public"
    subfolders = {}
    files =
        htaccess,
        htrouter,
        index.html
}

object "<u>.htaccess:File</u>" as htaccess {
    name = ".htaccess"
}

object "<u>.htrouter.php:File</u>" as htrouter {
    name = ".htrouter.php"
}

object "<u>index.html:File</u>" as index {
    name = "index.html"
}

object "<u>Include Path:Folder</u>" as IncludePath {
    name = "Include Path"
    subfolders = {}
    files = {}
}

object "<u>Remote Files:Folder</u>" as RemoteFiles {
    name = "Remote Files"
    subfolders = {}
    files = {}
}

root --* SourceFiles
root --* IncludePath
root --* RemoteFiles
SourceFiles --* phalcon
SourceFiles --* cache
SourceFiles --* public
public --* htaccess
public --* htrouter
public --* index

@enduml
